site_name: 现实的荒原
site_author: shrike505
site_url: https://shrike-505.github.io/
repo_name: shrike505
repo_url: https://github.com/shrike-505/shrike-505.github.io/
copyright: Copyright &copy; 2024 <a href="https://github.com/shrike-505" target="_blank">shrike505</a>
nav: 
- shrike505's blog: index.md
- 小说: 
  - stories/index.md
  - 正义: stories/Justice.md
  - 愚者: stories/Fool.md
  - 花椒: stories/Pepper.md
  - 蛋白: stories/Protein.md
  - 烟消: stories/Vanishment.md
  - 硝烟: stories/Gunpowdersmoke.md
  - 新车: stories/Newcar.md
  - 尺兵: stories/Weapon.md
  - 老鼠: stories/Mice.md
- 散文: 
  - thoughts/index.md
  - 痛风: thoughts/Gaut.md
  - 故乡: thoughts/Homesick.md
  - 羊杂: thoughts/Gut.md
  - 富贵: thoughts/Fortune.md 
  - 希音: thoughts/Unspoken.md
- 笔记:
  - notes/index.md
  - Computer Science:
    - CS61A: notes/ComputerScience/cs61a.md
    - 计算机系统Ⅰ: notes/ComputerScience/ComputerSystem1.md
    - 数据结构基础: notes/ComputerScience/FDS.md
  - 数理:
    - 线性代数Ⅱ: notes/MathematicsAndPhysics/LinearAlgebra.md
    - 数学分析Ⅱ: notes/MathematicsAndPhysics/Analysis.md
    - 普通物理学Ⅰ: notes/MathematicsAndPhysics/Physics1.md
    - 常微分方程: notes/MathematicsAndPhysics/ODE.md
    - 离散数学: notes/MathematicsAndPhysics/DiscreteMath.md
  - 托福相关: notes/Toefl.md
- 随笔:
    - casual/index.md
- 杂:
  - others/index.md
  - 年终总结: others/final.md
  - 暑假指南: others/summer_idle.md
theme: 
  name: material
  favicon: img/PP.png
  logo: img/PP.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  #font:(已用CSS实现)
   # text: Love Light
   # text: Sassy Frass
   # text: Lavishly Yours
   # text: Princess Sofia
  language: zh
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: theme
      primary: 1bdbe9b0
      toggle:
        icon: material/weather-night
        name: 光芒熄灭了。
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 把火点起来吧。

  features:
    - navigation.footer
    - navigation.path
    - navigation.indexes
    # - navigation.path
    # - toc.integrate 
    - navigation.top
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - toc.follow
    # - header.autohide
    # - announce.dismiss
  custom_dir: overrides
  
plugins:
  - blog:
      blog_dir: casual
      archive: false
      post_readtime_words_per_minute: 350
      post_date_format: full
      blog_toc: true
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
  - changelog
  - statistics:
      words_per_minute: 350
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      locale: zh
      type: date
      exclude: 
        - casual/*

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://fonts.font.im/css?family=Gloria+Hallelujah
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/changelogs.css
  - css/newcolor.css
  - css/newfonts.css

extra_javascript:
  - javascript/katex.js 
  # I've been meditating on the difference between MathJax and KaTeX.
  # - javascript/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://fastly.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  social:
        - icon: material/email
          link: mailto:<mikamidouya@outlook.com>
          name: E-mail